from django.contrib import admin
from frontend.models import HeaderLogo, FooterLogo, Loan, LoanDuration, LoanInterest, Investment, InvestmentInterest, InvestmentDuration, Post, Tags, Category, Comment, Reply, About, Title, Occupation, Service, Purpose, Statement, Team, Testimony, Newsletter, Mail, Career, Advert, Contact, ContactDetail, Faq, Event, Gallery
# Register your models here.

admin.site.register(Post)
admin.site.register(Tags)
admin.site.register(Category)
admin.site.register(Comment)
admin.site.register(Reply)
admin.site.register(Loan)
admin.site.register(LoanDuration)
admin.site.register(LoanInterest)
admin.site.register(Investment)
admin.site.register(InvestmentInterest)
admin.site.register(InvestmentDuration)
admin.site.register(About)
admin.site.register(Title)
admin.site.register(Service)
admin.site.register(Purpose)
admin.site.register(Statement)
admin.site.register(Team)
admin.site.register(Testimony)
admin.site.register(Newsletter)
admin.site.register(Mail)
admin.site.register(Career)
admin.site.register(Advert)
admin.site.register(Contact)
admin.site.register(ContactDetail)
admin.site.register(Occupation)
admin.site.register(Faq)
admin.site.register(Gallery)
admin.site.register(Event)
admin.site.register(HeaderLogo)
admin.site.register(FooterLogo)
