# Generated by Django 3.2 on 2023-05-29 22:00

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.CharField(max_length=255, null=True, verbose_name='Followed')),
                ('followed_by', models.CharField(max_length=255, null=True, verbose_name='Followed By')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True)),
                ('title', models.CharField(choices=[('', 'Select Title'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Alhaji', 'Alhaji'), ('Alhaja', 'Alhaja')], max_length=10, null=True, verbose_name='Title')),
                ('middlename', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('dob', models.DateField(null=True)),
                ('religion', models.CharField(choices=[('', 'Select Religion'), ('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional'), ('Others', 'Others')], max_length=20, null=True, verbose_name='Religion')),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('marital', models.CharField(choices=[('', 'Select Marital Status'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20, null=True, verbose_name='Marital Status')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Residential Address')),
                ('busstop', models.CharField(max_length=255, null=True, verbose_name='Nearest Bus Stop')),
                ('office', models.CharField(max_length=255, null=True, verbose_name='Office Address')),
                ('bio', models.TextField(blank=True, max_length=300, null=True, verbose_name='Biography')),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria')], max_length=10, null=True, verbose_name='Country')),
                ('state', models.CharField(max_length=150, null=True, verbose_name='State of Origin')),
                ('lga', models.CharField(max_length=150, null=True, verbose_name='LGA of Origin')),
                ('home', models.CharField(max_length=150, null=True, verbose_name='Home Town')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Link')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter Link')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram Link')),
                ('youtube', models.URLField(blank=True, max_length=255, null=True, verbose_name='Youtube Link')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='images/profile.png', upload_to='profile', verbose_name='Applicant Image')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.occupation', verbose_name='Occupation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['user'],
            },
        ),
    ]
